### ISSUE TITLE
npm run dev

### ISSUE THREAD

**Issue by caos2k** [mediamonks/richmedia-temple-server#6]
When the user enters the Project Name (during the question time @generator), if you insert a Project Name containing spaces, running dev.js will break and gives you this errors:

![screenshot 2018-10-23 at 13 54 06](https://user-images.githubusercontent.com/4586508/47358807-260ea800-d6cb-11e8-9372-ea7c6ffcc746.png)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.4.1
3 info using node@v10.11.0
4 verbose stack Error: Invalid name: "This is my project name"
4 verbose stack     at ensureValidName (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:335:15)
4 verbose stack     at Object.fixNameField (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/fixer.js:215:5)
4 verbose stack     at /usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:32:38
4 verbose stack     at Array.forEach (<anonymous>)
4 verbose stack     at normalize (/usr/local/lib/node_modules/npm/node_modules/normalize-package-data/lib/normalize.js:31:15)
4 verbose stack     at final (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:411:5)
4 verbose stack     at then (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:160:5)
4 verbose stack     at ReadFileContext.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/read-package-json/read-json.js:332:20)
4 verbose stack     at ReadFileContext.callback (/usr/local/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:78:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:235:13)
5 verbose cwd /Applications/MAMP/htdocs/test
6 verbose Darwin 18.0.0
7 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
8 verbose node v10.11.0
9 verbose npm  v6.4.1
10 error Invalid name: "This is my project name"
11 verbose exit [ 1, true ]

**Comment by caos2k** [comment]
removing this issue from here since it's being solved into Generator-Richmedia-Temple
